# DATA 467 Project: Data Analysis + Linear Models (AB_NYC_2019)
# Author: template generated by Codex
# Note: Although your prompt mentioned Python, the requested functions/packages are R-based.
# This script uses common R packages: readr, dplyr, ggplot2, car, broom.

# =========================
# 0) Load packages
# =========================
# If package missing, install it first:
# install.packages(c("readr", "dplyr", "ggplot2", "car", "broom", "tidyr", "forcats", "scales"))

library(readr)
library(dplyr)
library(ggplot2)
library(car)
library(broom)
library(tidyr)
library(forcats)
library(scales)

# =========================
# 1) Read data + basic checks
# =========================
file_path <- "/Users/ronnygottheway/Desktop/467 Spring/Projects/WorkSpace/data/raw/AB_NYC_2019.csv"

ab_raw <- read_csv(file_path, show_col_types = TRUE)

# Basic structure checks
dim(ab_raw)       # rows and columns
names(ab_raw)     # variable names
head(ab_raw)      # first 6 rows
str(ab_raw)       # structure and data types
summary(ab_raw)   # summary statistics

# =========================
# 2) Data cleaning
# =========================
# 2.1 Missing values overview (all variables)
missing_counts <- colSums(is.na(ab_raw))
missing_counts

# 2.2 Focus missing checks for key variables
ab_raw %>%
  summarise(
    missing_price = sum(is.na(price)),
    missing_reviews_per_month = sum(is.na(reviews_per_month)),
    missing_last_review = sum(is.na(last_review)),
    zero_price = sum(price == 0, na.rm = TRUE)
  )

# 2.3 Main variables for modeling
vars_needed <- c(
  "price", "room_type", "neighbourhood_group",
  "minimum_nights", "number_of_reviews", "reviews_per_month",
  "calculated_host_listings_count", "availability_365"
)

# Check if all required variables exist
setdiff(vars_needed, names(ab_raw))

# 2.4 Remove price == 0 and keep complete cases for model variables
ab_clean <- ab_raw %>%
  filter(!is.na(price), price > 0) %>%
  mutate(
    room_type = factor(room_type),
    neighbourhood_group = factor(neighbourhood_group)
  ) %>%
  filter(if_all(all_of(vars_needed), ~ !is.na(.x))) %>%
  mutate(log_price = log(price))

# Quick check after cleaning
dim(ab_clean)
summary(ab_clean$price)
summary(ab_clean$log_price)

# =========================
# 3) Variable selection + factor reference levels
# =========================
# Ensure selected variables exist in cleaned data
setdiff(c(vars_needed, "log_price"), names(ab_clean))

# Set reference groups as requested
ab_clean <- ab_clean %>%
  mutate(
    room_type = fct_relevel(room_type, "Private room"),
    neighbourhood_group = fct_relevel(neighbourhood_group, "Brooklyn")
  )

# Confirm levels
levels(ab_clean$room_type)
levels(ab_clean$neighbourhood_group)

# =========================
# 4) Data Analysis
# =========================

# 4.1 Descriptive statistics for quantitative variables
quant_vars <- c(
  "price", "log_price", "minimum_nights", "number_of_reviews",
  "reviews_per_month", "calculated_host_listings_count", "availability_365"
)

desc_stats <- ab_clean %>%
  select(all_of(quant_vars)) %>%
  summarise(
    across(
      everything(),
      list(
        mean = ~ mean(.x, na.rm = TRUE),
        median = ~ median(.x, na.rm = TRUE),
        sd = ~ sd(.x, na.rm = TRUE),
        min = ~ min(.x, na.rm = TRUE),
        q1 = ~ quantile(.x, 0.25, na.rm = TRUE),
        q3 = ~ quantile(.x, 0.75, na.rm = TRUE),
        max = ~ max(.x, na.rm = TRUE)
      ),
      .names = "{.col}_{.fn}"
    )
  )

desc_stats

# 4.2 Frequency + percentage tables for categorical variables
room_type_tab <- ab_clean %>%
  count(room_type) %>%
  mutate(percent = n / sum(n) * 100)

neigh_tab <- ab_clean %>%
  count(neighbourhood_group) %>%
  mutate(percent = n / sum(n) * 100)

room_type_tab
neigh_tab

# 4.3 Price distribution focus
summary(ab_clean$price)
quantile(ab_clean$price, probs = c(0, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99, 1), na.rm = TRUE)

# 4.4 Plots
# (1) Histogram of price
p1 <- ggplot(ab_clean, aes(x = price)) +
  geom_histogram(bins = 60, fill = "steelblue", color = "white") +
  scale_x_continuous(labels = dollar) +
  labs(title = "Histogram of Price", x = "Price (USD)", y = "Count") +
  theme_minimal()
p1

# (2) Histogram of log_price
p2 <- ggplot(ab_clean, aes(x = log_price)) +
  geom_histogram(bins = 60, fill = "darkorange", color = "white") +
  labs(title = "Histogram of Log(Price)", x = "log_price", y = "Count") +
  theme_minimal()
p2

# (3) Boxplot by room_type (use log_price to reduce skew impact)
p3 <- ggplot(ab_clean, aes(x = room_type, y = log_price, fill = room_type)) +
  geom_boxplot(alpha = 0.8, outlier.alpha = 0.2) +
  labs(title = "Log(Price) by Room Type", x = "Room Type", y = "log_price") +
  theme_minimal() +
  theme(legend.position = "none")
p3

# (4) Boxplot by neighbourhood_group
p4 <- ggplot(ab_clean, aes(x = neighbourhood_group, y = log_price, fill = neighbourhood_group)) +
  geom_boxplot(alpha = 0.8, outlier.alpha = 0.2) +
  labs(title = "Log(Price) by Neighbourhood Group", x = "Neighbourhood Group", y = "log_price") +
  theme_minimal() +
  theme(legend.position = "none")
p4

# (5) Scatter plots: log_price vs selected quantitative predictors
p5a <- ggplot(ab_clean, aes(x = minimum_nights, y = log_price)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(title = "log_price vs minimum_nights") +
  theme_minimal()
p5a

p5b <- ggplot(ab_clean, aes(x = availability_365, y = log_price)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(title = "log_price vs availability_365") +
  theme_minimal()
p5b

# (6) Correlation matrix for quantitative variables
cor_mat <- ab_clean %>%
  select(all_of(quant_vars)) %>%
  cor(use = "complete.obs")

round(cor_mat, 3)

# Optional quick heatmap using ggplot2 only
cor_df <- as.data.frame(as.table(cor_mat))
names(cor_df) <- c("Var1", "Var2", "Correlation")

p6 <- ggplot(cor_df, aes(x = Var1, y = Var2, fill = Correlation)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limits = c(-1, 1)) +
  theme_minimal() +
  labs(title = "Correlation Matrix (Quantitative Variables)", x = NULL, y = NULL)
p6

# =========================
# 5) Linear Models (Multiple Regression)
# =========================

# Model 1: categorical predictors only
model1 <- lm(log_price ~ room_type + neighbourhood_group, data = ab_clean)
summary(model1)

# Model 2: add quantitative predictors
model2 <- lm(
  log_price ~ room_type + neighbourhood_group +
    minimum_nights + number_of_reviews + reviews_per_month +
    calculated_host_listings_count + availability_365,
  data = ab_clean
)
summary(model2)

# Tidy tables with 95% CI
m1_tidy <- tidy(model1, conf.int = TRUE, conf.level = 0.95)
m2_tidy <- tidy(model2, conf.int = TRUE, conf.level = 0.95)

m1_tidy
m2_tidy

# R-squared and Adjusted R-squared comparison
model_compare <- bind_rows(
  glance(model1) %>% mutate(model = "Model 1"),
  glance(model2) %>% mutate(model = "Model 2")
) %>%
  select(model, r.squared, adj.r.squared, sigma, statistic, p.value, df)

model_compare

# Nested-model comparison (ANOVA F-test)
anova(model1, model2)

# =========================
# 6) Coefficient interpretation helpers (log-price -> % change)
# =========================
# Percent interpretation function: 100*(exp(beta)-1)
interpret_percent <- function(beta) {
  100 * (exp(beta) - 1)
}

# Example: extract key coefficients from Model 2 and convert
key_coef <- broom::tidy(model2) %>%
  filter(grepl("room_type|neighbourhood_group", term)) %>%
  mutate(percent_change = interpret_percent(estimate))

key_coef

# =========================
# 7) Model diagnostics
# =========================

# Base R diagnostic panel
par(mfrow = c(2, 2))
plot(model2)
par(mfrow = c(1, 1))

# VIF for multicollinearity
vif_values <- car::vif(model2)
vif_values

# Cook's distance for influential points
cooks_d <- cooks.distance(model2)
summary(cooks_d)

# Common threshold: 4/n
n <- nrow(ab_clean)
cook_threshold <- 4 / n
influential_idx <- which(cooks_d > cook_threshold)
length(influential_idx)
head(influential_idx)

# Optional plot for Cook's D
plot(cooks_d, pch = 20, cex = 0.5, main = "Cook's Distance", ylab = "Cook's D")
abline(h = cook_threshold, col = "red", lty = 2)

# =========================
# 8) Inference + prediction
# =========================

# Significance + CI already in m2_tidy. If needed, print only key rows:
m2_tidy %>%
  filter(term != "(Intercept)") %>%
  arrange(p.value)

# Construct a new listing for prediction
new_listing <- tibble(
  neighbourhood_group = factor("Manhattan", levels = levels(ab_clean$neighbourhood_group)),
  room_type = factor("Entire home/apt", levels = levels(ab_clean$room_type)),
  minimum_nights = 3,
  number_of_reviews = 20,
  reviews_per_month = 1.5,
  calculated_host_listings_count = 2,
  availability_365 = 180
)

# Predicted log_price with CI and PI
pred_conf <- predict(model2, newdata = new_listing, interval = "confidence", level = 0.95)
pred_pred <- predict(model2, newdata = new_listing, interval = "prediction", level = 0.95)

pred_conf
pred_pred

# Convert from log scale back to price scale (exp transformation)
pred_price_conf <- exp(pred_conf)
pred_price_pred <- exp(pred_pred)

pred_price_conf
pred_price_pred

# =========================
# 9) Paper-ready English templates
# =========================

cat("\n--- Data Analysis paragraph template ---\n")
cat(
"We first conducted descriptive analysis of the cleaned Airbnb NYC dataset. ",
"The distribution of price was right-skewed, while log(price) appeared substantially more symmetric. ",
"Frequency tables showed that listing composition differed across room types and neighbourhood groups. ",
"Boxplots suggested clear differences in log(price) by room_type and neighbourhood_group, motivating their inclusion in regression models.\n",
sep = ""
)

cat("\n--- Linear Models paragraph template ---\n")
cat(
"We estimated multiple linear regression models using log(price) as the response variable. ",
"Model 1 included only room_type and neighbourhood_group. ",
"Model 2 additionally controlled for minimum_nights, number_of_reviews, reviews_per_month, calculated_host_listings_count, and availability_365. ",
"Model 2 achieved higher R-squared and adjusted R-squared than Model 1, indicating improved explanatory power after adding quantitative covariates.\n",
sep = ""
)

cat("\n--- Diagnostics paragraph template ---\n")
cat(
"Diagnostic plots for Model 2 suggest that linearity is broadly reasonable. ",
"Residual spread indicates some heteroscedasticity, but not severe enough to invalidate the overall pattern. ",
"The Q-Q plot shows residuals are approximately normal with mild tail deviations. ",
"VIF values do not indicate severe multicollinearity, and Cook's distance identifies only a limited number of potentially influential observations.\n",
sep = ""
)

# =========================
# 10) Common error fixes (quick notes)
# =========================
# If you get: cannot open file -> double-check file_path and spaces in folder names.
# If you get: package not found -> run install.packages(...) first.
# If factor relevel fails -> check exact level spelling using unique(ab_clean$room_type).

